import tensorflow as tf
print("Matrix Multiplication Demo")
x=tf.constant([1,2,10,1,2,6],shape=[2,3])
print(x)
y=tf.constant([5,8,12,10,1,12],shape=[3,2])
print(y)
z=tf.matmul(x,y)
print("Product:",z)
e_matrix_A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32,name="matrixA")
print("Matrix A:\n\n",format(e_matrix_A))
eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A)
print("Eigen Vectors:\n\nEigen Values:\n\n".format(eigen_vectors_A,eigen_values_A))
